openapi: 3.0.3
info: 
  title: StreetGotTalent
  description: API for StreetGotTalent application
  version: 1.0.0
  contact:
    email: ckamsi04@gmail.com
servers:
  - url: http://localhost:3000/api/v1
  - url: https://carxperto.onrender.com/api/v1

schemes: [http,https]

tags:
  - season
  - contestant
  - payment
  - admin

paths:
  
components:
  securitySchemes:
    BearerAuth:
      type: https
      scheme: bearer
      bearerFormat: JWT