openapi: 3.0.3
info: 
  title: StreetGotTalent
  description: API for StreetGotTalent application
  version: 1.0.0
  contact:
    email: ckamsi04@gmail.com
servers:
  - url: http://localhost:3000/api/v1
  - url: https://carxperto.onrender.com/api/v1

schemes: [http,https]

tags:
  - name: auth
  - name: seller
  - name: car

paths:
  
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      required:
        - email
        - password
        - username
        - fullname
      properties:
        username:
          type: string
          description: A unique username for authentication
        password:
          type: string
          description: A secure password for authentication
        email:
          type: string
          description: A unique email for authentication
        fullname:
          type: string
          description: First and lastname of the user separated by a space
        account_type:
          type: string
          description: Specifies the type of user
